# Generated by Django 4.1.2 on 2023-06-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem_model", old_name="title", new_name="task",
        ),
        migrations.RemoveField(model_name="todoitem_model", name="updated_at",),
    ]
